# Generated by Django 5.1.4 on 2025-01-05 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blogs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headline', models.CharField(max_length=200)),
                ('date', models.DateField()),
                ('subheading', models.CharField(max_length=300)),
                ('description', models.TextField()),
            ],
        ),
    ]
