# Generated by Django 5.1.4 on 2025-01-05 10:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogs',
            old_name='subheading',
            new_name='subtitle',
        ),
        migrations.RenameField(
            model_name='blogs',
            old_name='headline',
            new_name='title',
        ),
        migrations.RemoveField(
            model_name='blogs',
            name='date',
        ),
        migrations.AddField(
            model_name='blogs',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='blogs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='blogs',
            name='created_at',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
