# Generated by Django 5.1.4 on 2025-01-13 06:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0005_remove_blogs_author'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogs',
            old_name='img',
            new_name='image',
        ),
    ]
